# -*- coding: utf-8 -*-
"""M25MAC012-A2-Prob1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X8VR1Kftb16ReevYR-BOa-QDsIKJZHeP

**SMITHI SURESHAN**

**M25MAC012**      
**Assignment2- Problem 1**

Importing Libraries
"""

!pip install nltk wordcloud scikit-learn beautifulsoup4
import re
import nltk
import numpy as np
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
from wordcloud import WordCloud#it gives word cloud visualization
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from nltk.corpus import stopwords
from collections import Counter#it counts frequency of word

nltk.download('punkt')
nltk.download('stopwords')

"""Uploading file"""

from google.colab import files
uploaded = files.upload()
file_path = list(uploaded.keys())[0]

"""Reading entire file"""

with open(file_path, 'r', encoding='utf-8') as f:
    text = f.read()
text = BeautifulSoup(text, "html.parser").get_text()  # it removes html tags

"""Cleaning text"""

text = re.sub(r'http\S+|www\S+', ' ', text) #it removes URLs
text = re.sub(r'\bdot\b', ' ', text)
text = re.sub(r'\bcall\b', ' ', text)
# Common unwanted words
boilerplate = [
    "home","index","page","back","next","menu","search",
    "click","read","more","view",
    "iit","jodhpur","indian","institute",
    "department","program","course","semester",
    "application","admission","registration",
    "system","process","based","download file","http",
]
#it removes boiler word
for word in boilerplate:
    text = re.sub(rf'\b{word}\b', ' ', text, flags=re.IGNORECASE)

text = text.lower() #for converting into lowercase
text = re.sub(r'[^a-z\s]', ' ', text)#for removing numbers and symbols and keep only alphabets
text = re.sub(r'\s+', ' ', text).strip()#it removes extra spaces

"""Stopwords and tokenization"""

nltk.download('punkt_tab')
stop_words = set(stopwords.words('english'))
important_words = {"student","exam","phd","research"} # these are words which we need for our implementation
stop_words = stop_words - important_words #it removes important worrds from stop words
#adding unwanted words
stop_words.update([
    "call","page","home","back","index",
    "year","may","also","shall","include","download file"
])
#it breaks text into sentences
sentences_raw = nltk.sent_tokenize(text)

sentences = []
for raw_sent in sentences_raw:
    sent_tokens = nltk.word_tokenize(raw_sent)#it breaks sentences into words
    cleaned_sent_tokens = [w for w in sent_tokens if w not in stop_words and len(w) > 2]#it removes stopwords and very short words
    if cleaned_sent_tokens:
        sentences.append(cleaned_sent_tokens)

tokens = [w for s in sentences for w in s]#it flattens tokens list
freq = Counter(tokens)#it counts frequency of words

important_words = {
    "student","students","research","phd","exam",
    "thesis","masters","btech","mtech",
    "course","degree","engineering","science","data"
}
#it removes rarely appearing words
tokens = [w for w in tokens if freq[w] >= 3 or w in important_words]
freq = Counter(tokens)# it counts frequency

sentences = [[w for w in s if freq[w] >= 5] for s in sentences]

print(freq)# print frequency

"""Saving Clean corpus after preprocessing and Data Statistics"""

with open("clean_corpus.txt", "w") as f:
    for s in tokens:
        f.write(s + "\n")

print("Clean corpus saved")
vocab = list(set(tokens))# it creates vocabulary
print("\nSTATISTICS")
print("Total Documents:", len(sentences_raw))
print("Total Tokens:", len(tokens))
print("Vocabulary Size:", len(set(tokens)))

"""Word Cloud"""

wc = WordCloud(width=900, height=450, background_color='white', max_words=100)
wc.generate(" ".join(tokens))
plt.imshow(wc)
plt.axis("off")
plt.title("Word Cloud")
plt.show()

"""Negative Sampling Distribution"""

pow_freq = np.array([freq[w]**0.75 for w in vocab])
neg_dist = pow_freq / pow_freq.sum()

vocab = list(set(tokens))#it creates word index mapping
word2idx = {w:i for i,w in enumerate(vocab)}# mapping word to index
idx2word = {i:w for w,i in word2idx.items()}#mapping index to word
#model parameters
vocab_size = len(vocab)
embedding_dim = 300
window = 5
#it generates training data for CBOW
def generate_cbow_data(sentences):
    data = []
    for sent in sentences:
        for i in range(window, len(sent)-window):
            context = [word2idx[sent[j]] for j in range(i-window, i+window+1) if j != i]
            target = word2idx[sent[i]]
            data.append((context, target))
    return data
#it generates training data for Skip Gram
def generate_skipgram_data(sentences):
    data = []
    for sent in sentences:
        for i, word in enumerate(sent):
            target = word2idx[word]
            for j in range(max(0, i-window), min(len(sent), i+window+1)):
                if j != i:
                    context = word2idx[sent[j]]
                    data.append((target, context))
    return data
#it prepares data for training
cbow_data = generate_cbow_data(sentences)
skip_data = generate_skipgram_data(sentences)
#initializing weight matrices
W1 = np.random.randn(vocab_size, embedding_dim)
W2 = np.random.randn(embedding_dim, vocab_size)
W1_s = np.random.randn(vocab_size, embedding_dim)
W2_s = np.random.randn(embedding_dim, vocab_size)

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

def one_hot(i):
    vec = np.zeros(vocab_size)
    vec[i] = 1
    return vec

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def cosine(a, b):
    return np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

#initializing CBOW weights
W_target_c = np.random.randn(vocab_size, embedding_dim)
W_context_c = np.random.randn(vocab_size, embedding_dim)

"""Training for CBOW"""

#parameters for training
epochs = 10
lr = 0.01
neg_samples = 10
#CBOW loop for training
for epoch in range(epochs):
    loss = 0

    for context, target in cbow_data:

        v_c = np.mean([W_context_c[i] for i in context], axis=0)
        v_t = W_target_c[target]

        score = sigmoid(np.dot(v_t, v_c))
        loss += -np.log(score + 1e-9)

        grad = lr * (score - 1)

        W_target_c[target] -= grad * v_c
        for i in context:
            W_context_c[i] -= grad * v_t / len(context)
        neg_indices = np.random.choice(
    vocab_size, neg_samples, p=neg_dist, replace=False)

        for neg in neg_indices:
            v_n = W_target_c[neg]

            score_neg = sigmoid(np.dot(v_n, v_c))
            loss += -np.log(1 - score_neg + 1e-9)

            grad = lr * score_neg

            W_target_c[neg] -= grad * v_c
            for i in context:
                W_context_c[i] -= grad * v_n / len(context)

    print(f"CBOW Epoch {epoch+1}, Loss: {loss:.2f}")

#Initializing Skip gram weights
embedding_dim = 300
W_target_s = np.random.randn(vocab_size, embedding_dim)
W_context_s = np.random.randn(vocab_size, embedding_dim)

"""Training for Skip Gram"""

#parameters for training
epochs = 10
lr = 0.01
neg_samples = 10
#Training loop for skip gram
for epoch in range(epochs):
    loss = 0

    for target, context in skip_data:

        v_t = W_target_s[target]
        v_c = W_context_s[context]

        score = sigmoid(np.dot(v_t, v_c))
        loss += -np.log(score + 1e-9)

        grad = lr * (score - 1)

        W_target_s[target] -= grad * v_c
        W_context_s[context] -= grad * v_t

        neg_indices = np.random.choice(
    vocab_size, neg_samples, p=neg_dist, replace=False)

        for neg in neg_indices:
            v_n = W_context_s[neg]

            score_neg = sigmoid(np.dot(v_t, v_n))
            loss += -np.log(1 - score_neg + 1e-9)

            grad = lr * score_neg

            W_target_s[target] -= grad * v_n
            W_context_s[neg] -= grad * v_t

    print(f"Skip-gram Epoch {epoch+1}, Loss: {loss:.2f}")

#Cosine Similarity
def cosine(a, b):#for getting cosine similarity between vectores
    return np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))
#it searches for nearest words
def nearest(word, W):
    if word not in word2idx:#it checks whether word exists in vocabulary
        print("Not found")
        return

    vec = W[word2idx[word]]#it gets vector of input
    sims = []#it stores similarity scores
#it compares all words available in vocabulary
    for w in vocab:
        if w != word:#it skips same word
            sims.append((w, cosine(vec, W[word2idx[w]])))#similarity score we got is stored

    sims = sorted(sims, key=lambda x: x[1], reverse=True)[:5]#it uses similarity for sortingg words to get top 5 words

    print(f"\nTop words for '{word}':")
    for w, s in sims:
        print(w, f"{s:.3f}")#it gives similarity upto 3 decimal places

def analogy(a, b, c, W):
    if a not in word2idx or b not in word2idx or c not in word2idx: #it checks whether all words exist
        print(f"Missing word in analogy: {a}, {b}, {c}")
        return

    vec = W[word2idx[b]] - W[word2idx[a]] + W[word2idx[c]]#vector=b-a+c

    sims = []# it stores similarity scores
    #it compares with all words
    for w in vocab:
        if w not in [a, b, c]:
            sims.append((w, cosine(vec, W[word2idx[w]])))
#it sorts and gets top 5 words
    sims = sorted(sims, key=lambda x: x[1], reverse=True)[:5]

    print(f"\n{a}:{b} :: {c}: ?")
    for w, s in sims:
        print(w, f"{s:.3f}")

"""Normalizing every vector and makes vector length =1"""

def normalize(W):
    return W / np.linalg.norm(W, axis=1, keepdims=True)#each vector is normalized row-wise
#Normalizing CBOW and Skip-gram embeddings
W_target_c = normalize(W_target_c)
W_target_s = normalize(W_target_s)

"""Prints Nearest words, similar words using CBOW embeddings and Skip gram embeddings, Testing Analogies"""

print("\n==CBOW ===")
#using CBOW embeddings for finding similar words
for w in ["research","student","phd","exam"]:
    nearest(w, W_target_c)
#using Skip-gram embeddings for finding similar words
print("\n==SKIP-GRAM===")
for w in ["research","student","phd","exam"]:
    nearest(w, W_target_s)

#testing analogy with CBOW
print("\n==ANALOGY (CBOW)===")
analogy("engineering", "technology", "science", W_target_c)
analogy("student", "research", "engineering", W_target_c)
analogy("data", "science", "engineering", W_target_c)

#testing analogy with skip-gram
print("\n==ANALOGY (SKIP-GRAM)===")
analogy("engineering", "technology", "science", W_target_s)
analogy("student", "research", "engineering", W_target_s)
analogy("data", "science", "engineering", W_target_s)

"""Visualization using PCA"""

def visualize(W, words):
    vecs, labels = [], [] #it stores vectors and labels
#it collects vectors for given word
    for w in words:
        if w in word2idx:
            vecs.append(W[word2idx[w]])
            labels.append(w)

    vecs = np.array(vecs)# converting list to numpy array

    pca = PCA(n_components=2)#using PCA to reduce dimensions
    reduced = pca.fit_transform(vecs)
#Plotting  figure
    plt.figure()
    for i, word in enumerate(labels):
        plt.scatter(reduced[i,0], reduced[i,1])
        plt.text(reduced[i,0], reduced[i,1], word)
    plt.title("PCA")
    plt.show()
#words that we want to visualize
words = ["research","engineering","science","technology",
         "student","phd","exam","thesis","data","learning"]

print("\nCBOW Visualization")
visualize(W_target_c, words)

print("\nSkip-gram Visualization")
visualize(W_target_s, words)

word = "science"
idx = word2idx[word]
vector = W1[idx]
vector_300 = vector[:300]
print(word, "-", ", ".join([str(round(v,4)) for v in vector_300]))

"""---------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

By using Built-in libraries for comparison

Importing Libraries
"""

!pip install gensim nltk wordcloud scikit-learn beautifulsoup4
import re
import nltk
import numpy as np
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from gensim.models import Word2Vec
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from nltk.corpus import stopwords
from collections import Counter
nltk.download('punkt')  #it is for sentence tokenization
nltk.download('stopwords') #it is for removing common words

"""Uploading file"""

from google.colab import files
uploaded = files.upload()
file_path = list(uploaded.keys())[0]

"""Reading Entire file"""

with open(file_path, 'r', encoding='utf-8') as f:
    text = f.read()

"""Text Cleaning"""

text = BeautifulSoup(text, "html.parser").get_text()#it removes HTML tags
text = re.sub(r'http\S+|www\S+', ' ', text)#it removes URL
text = re.sub(r'\bdot\b', ' ', text)
text = re.sub(r'\bcall\b', ' ', text)
#Common words in websites
boilerplate = [
    "home","index","page","back","next","menu","search",
    "click","read","more","view",
    "iit","jodhpur","indian","institute",
    "department","program","course","semester",
    "application","admission","registration",
    "system","process","based","download file"
]
#it removes unwanted words
for word in boilerplate:
    text = re.sub(rf'\b{word}\b', ' ', text, flags=re.IGNORECASE)

text = text.lower()#it converts text to lowercase
text = re.sub(r'[^a-z\s]', ' ', text) #it removes numbers and symbols and keep only alphabets
text = re.sub(r'\s+', ' ', text).strip()# it removes extra spaces

nltk.download('punkt_tab')

stop_words = set(stopwords.words('english'))
important_words = {"student","exam","phd","research"}
stop_words = stop_words - important_words#it removes important words from stopwords

stop_words.update(
    ["call","page","home","back","index",
    "year","may","also","shall","include","download file"]
)
#Tokenization
sentences = nltk.sent_tokenize(text)#splitting text into sentences
tokenized = []
for sent in sentences:
    words = nltk.word_tokenize(sent) #splitting sentence into words
    words = [w for w in words if w not in stop_words and len(w) > 2]# it removes stopwords and very short words and keep meaningful sentences
    if words:
        tokenized.append(words)

tokens = [w for s in tokenized for w in s]#flatten all words into one list
freq = Counter(tokens)#it count frequency of each word
sentences = [[w for w in s if freq[w] < 500] for s in tokenized if len(s) > 0]#it removes words which come frequently

print(freq)#it prinyts frequency of words

"""Saving clean corpus"""

with open("clean_corpus.txt", "w") as f:
    for s in sentences:
        f.write(" ".join(s) + "\n")

print("Clean corpus saved")

"""Total Documents, tokens, Vocabulary Size"""

tokens = [w for s in sentences for w in s]#again calculating tokens after filtering
print("\nSTATISTICS")
print("Total Documents:", len(sentences))
print("Total Tokens:", len(tokens))
print("Vocabulary Size:", len(set(tokens)))

"""Word Cloud"""

wc = WordCloud(
    width=900,
    height=450,
    background_color='white',
    max_words=100
).generate(" ".join(tokens))

plt.imshow(wc)
plt.axis("off")
plt.title("Word Cloud")
plt.show()

"""Training Multiple Models"""

#various configurations for testing model performance
configs = [
    {"vector_size":50, "window":3, "negative":3},
    {"vector_size":100, "window":5, "negative":5},
    {"vector_size":200, "window":7, "negative":10}
]

models = []
#training model with different settings
for config in configs:
    print("\nTraining config:", config)
#CBOW model
    cbow = Word2Vec(
        sentences,
        vector_size=config["vector_size"],
        window=config["window"],
        negative=config["negative"],
        min_count=2,
        sg=0,
        epochs=100
    )
#Skip gram model
    skip = Word2Vec(
        sentences,
        vector_size=config["vector_size"],
        window=config["window"],
        negative=config["negative"],
        min_count=2,
        sg=1,
        epochs=100
    )

    models.append((config, cbow, skip))

config, cbow_model, skip_model = models[1]

"""Finding nearest top 5 words"""

#it finds similar words
def nearest(model, word):
    print(f"\nTop 5 for '{word}':")
    if word in model.wv:
        for w,s in model.wv.most_similar(word, topn=5):
            print(w, f"{s:.3f}")
    else:
        print("Not in vocab")
#using CBOW for finding similar words
print("\n===== CBOW =====")
for w in ["research","student","phd","exam"]:
    nearest(cbow_model, w)
#using Skip gram for finding similar words
print("\n===== SKIP-GRAM =====")
for w in ["research","student","phd","exam"]:
    nearest(skip_model, w)

"""Analogies and testing various analogies"""

def analogy(model, a, b, c):
    print(f"\n{a}:{b} :: {c}: ?")
    try:
        result = model.wv.most_similar(positive=[b,c], negative=[a], topn=3)
        for w,s in result:
            print(w, f"{s:.3f}")
    except:
        print("Words missing")
#testing various analogies using cbow
print("\n===== ANALOGIES (CBOW) =====")
analogy(cbow_model, "engineering", "technology", "science")
analogy(cbow_model, "student", "research", "engineering")
analogy(cbow_model, "data", "science", "engineering")
#testing analogies using skip gram
print("\n===== ANALOGIES (SKIP-GRAM) =====")
analogy(skip_model, "engineering", "technology", "science")
analogy(skip_model, "student", "research", "engineering")
analogy(skip_model, "data", "science", "engineering")

"""Visualizing using PCA and t-SNE"""

def visualize(model, words):
    vecs, labels = [], []
#collecting vectors of given worrds
    for w in words:
        if w in model.wv:
            vecs.append(model.wv[w])
            labels.append(w)

    print(f"Using {len(labels)} words for visualization")

    vecs_array = np.array(vecs)

    pca = PCA(n_components=2)#using PCA to reduce dimensions
    reduced = pca.fit_transform(vecs_array)

    plt.figure(figsize=(8,6))
    for i, word in enumerate(labels):
        plt.scatter(reduced[i,0], reduced[i,1])
        plt.text(reduced[i,0], reduced[i,1], word)

    plt.title("PCA Visualization")
    plt.show()
#Using t-SNE
    if len(vecs_array) > 10:
        tsne = TSNE(n_components=2, perplexity=5, random_state=42)
        reduced = tsne.fit_transform(vecs_array)

        plt.figure(figsize=(8,6))
        for i, word in enumerate(labels):
            plt.scatter(reduced[i,0], reduced[i,1])
            plt.text(reduced[i,0], reduced[i,1], word)

        plt.title("t-SNE Visualization")
        plt.show()
    else:
        print("Not enough words for t-SNE")
#words for visualizing
words = [
    "research","engineering","science","technology",
    "student","phd","exam","thesis","project",
    "data","analysis","learning","model",
    "course","degree","education","university"
]

print("\nCBOW Visualization")
visualize(cbow_model, words)

print("\nSkip-gram Visualization")
visualize(skip_model, words)